services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypass;
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
